# If image width/height are modified, make sure to modify the included blank image (head_camera.png) used by the image_publisher node
image_width: 1280
image_height: 720
# If image width/height are modified, make sure to modify the included blank image (head_camera.png) used by the image_publisher node

camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [648.483, 0, 642.119, 0, 648.483, 361.563, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.03273622486521822, -0.03871815017502053, 0.006272008680574142, -0.00642853526402813, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [648.483, 0, 642.119, 0, 0, 648.483, 361.563, 0, 0, 0, 1, 0]

