<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="tracebot_mockup" params="robot_mount_offset_x
                                              robot_mount_offset_y
                                              robot_mount_offset_z
                                              robot_mount_offset_theta
                                              robot_mount_height
                                              robot_mount_length
                                              robot_mount_width
                                              robot_base_tilt
                                              left_arm
                                              right_arm
                                              camera_mount_offset_z">
    <!-- Base -->
    <link name="base_link"/>
    
    <joint name="robot_mount_base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="robot_mount_base"/>
    </joint>

    <link name="robot_mount_base">
      <visual>
        <origin xyz="0 0 ${robot_mount_height/2}" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://tracebot_mockup_description/meshes/stand.stl" />
        </geometry>
        <material name="grey">
          <color rgba="0.6 0.6 0.6 1.0"/>
        </material>
      </visual>
    </link>
    
    
    <!-- Left Arm Mount -->
    <joint name="left_robot_mount_joint" type="fixed">
      <origin xyz="${-robot_mount_offset_x} 0 ${robot_mount_height-robot_mount_offset_z}" rpy="0 ${-pi/2+robot_base_tilt} 0"/>
      <parent link="robot_mount_base"/>
      <child link="left_robot_mount"/>
    </joint>
    
    <link name="left_robot_mount"/>
    
    <!-- Right Arm Mount -->
    <joint name="right_robot_mount_joint" type="fixed">
      <origin xyz="${robot_mount_offset_x} 0 ${robot_mount_height-robot_mount_offset_z}" rpy="0 ${pi/2-robot_base_tilt} 0"/>
      <parent link="robot_mount_base"/>
      <child link="right_robot_mount"/>
    </joint>
    
    <link name="right_robot_mount"/>
    
    <!-- Camera Mount -->
    <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />
    
    <joint name="camera_mount_joint" type="fixed">
      <origin xyz="0 0 ${robot_mount_height+camera_mount_offset_z}" rpy="0 0 0"/>
      <parent link="robot_mount_base"/>
      <child link="camera_mount"/>
    </joint>
    
    <link name="camera_mount"/>
    
    <xacro:sensor_d435 parent="camera_mount" 
      use_nominal_extrinsics="false" 
      add_plug="false" 
      use_mesh="true"
      name="tracebot_camera">
      <origin xyz="0 0 0" rpy="0 0.785398 1.5708"/>
    </xacro:sensor_d435>
  </xacro:macro>
</robot>
