<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro"/>

  <xacro:macro name="tracebot_mockup" params="robot_mount_offset_x
                                              robot_mount_offset_y
                                              robot_mount_offset_z
                                              robot_mount_offset_theta
                                              robot_mount_height
                                              robot_mount_length
                                              robot_mount_width
                                              robot_base_tilt
                                              left_arm
                                              right_arm">

    <!-- Base -->
    <link name="base_link"/>

    <link name="robot_mount_base">
      <visual>
        <origin xyz="0 0 ${robot_mount_height/2}" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file:///home/benrjg/astech_wss/tracebot_mockup_ws/src/tracebot_mockup/tracebot_mockup_description/meshes/stand.stl" />
        </geometry>
        <material name="grey">
          <color rgba="0.6 0.6 0.6 1.0"/>
        </material>
      </visual>
    </link>

    <joint name="robot_mount_base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="robot_mount_base"/>
    </joint>

    <!-- Left Arm Mount -->
    <link name="left_robot_mount"/>

    <joint name="left_robot_mount_joint" type="fixed">
      <origin xyz="${-robot_mount_offset_x} 0 ${robot_mount_height-robot_mount_offset_z}" rpy="0 ${-pi/2+robot_base_tilt} 0"/>
      <parent link="robot_mount_base"/>
      <child link="left_robot_mount"/>
    </joint>

    <!-- Right Arm Mount -->
    <link name="right_robot_mount"/>

    <joint name="right_robot_mount_joint" type="fixed">
      <origin xyz="${robot_mount_offset_x} 0 ${robot_mount_height-robot_mount_offset_z}" rpy="0 ${pi/2-robot_base_tilt} 0"/>
      <parent link="robot_mount_base"/>
      <child link="right_robot_mount"/>
    </joint>

  <!--Add parameters to robot arms-->
    <xacro:ur_robot prefix="left_"
      joint_limits_parameters_file="$(find ur_description)/config/$(arg left_arm)/joint_limits.yaml"
      kinematics_parameters_file="$(find ur_description)/config/$(arg left_arm)/default_kinematics.yaml"
      physical_parameters_file="$(find ur_description)/config/$(arg left_arm)/physical_parameters.yaml"
      visual_parameters_file="$(find ur_description)/config/$(arg left_arm)/visual_parameters.yaml"
      transmission_hw_interface="hardware_interface/VelocityJointInterface"
      safety_limits="false"
      safety_pos_margin="0.15"
      safety_k_position="20"/>
    <joint name="left_base_link_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="left_robot_mount"/>
      <child link="left_base_link"/>
    </joint>

    <xacro:ur_robot prefix="right_"
      joint_limits_parameters_file="$(find ur_description)/config/$(arg right_arm)/joint_limits.yaml"
      kinematics_parameters_file="$(find ur_description)/config/$(arg right_arm)/default_kinematics.yaml"
      physical_parameters_file="$(find ur_description)/config/$(arg right_arm)/physical_parameters.yaml"
      visual_parameters_file="$(find ur_description)/config/$(arg right_arm)/visual_parameters.yaml"
      transmission_hw_interface="hardware_interface/VelocityJointInterface"
      safety_limits="false"
      safety_pos_margin="0.15"
      safety_k_position="20"/>
    <joint name="right_base_link_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="right_robot_mount"/>
      <child link="right_base_link"/>
    </joint>
  </xacro:macro>
</robot>
